### ISSUE TITLE
Panics

### ISSUE THREAD

**Issue by Rambatino** [kelindar/binary#10]
Hello, thanks for the great library.

We've encountered some issues with panicing pointers.

``` golang
func main() {
	t := time.Now()
	data := []*A{{&t}}
	b, _ := binary.Marshal(data)
	var i []*A
	binary.Unmarshal(b, &i)

	data2 := []*B{{t}}
	b2, _ := binary.Marshal(data2)
	var j []*B
	binary.Unmarshal(b2, &j)
	log.Println(j)

	data3 := []*B{}
	b3, _ := binary.Marshal(data3)
	var h []*B
	binary.Unmarshal(b3, &h)
	log.Println(h)
}

type A struct {
	T *time.Time
}

type B struct {
	T time.Time
}
```

They all break in the same part:

``` bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x109bfea]

goroutine 1 [running]:
time.(*Time).UnmarshalBinary(0x2, {0xc0000b2130, 0x1, 0x1})
	/usr/local/go/src/time/time.go:1234 +0x8a
reflect.Value.call({0x10e9dc0, 0xc0000ac0b0, 0x12285b8}, {0x10ec1f5, 0x4}, {0xc0000d3c98, 0x1, 0xc0000d3c10})
	/usr/local/go/src/reflect/value.go:543 +0x814
reflect.Value.Call({0x10e9dc0, 0xc0000ac0b0, 0xf}, {0xc0000d3c98, 0x1, 0x1})
	/usr/local/go/src/reflect/value.go:339 +0xc5
github.com/kelindar/binary.(*customCodec).DecodeTo(0x10dbd40, 0xc000098450, {0x10e9dc0, 0xc0000ac0b0, 0xc0000ac0b0})
	/Users/mark/go/pkg/mod/github.com/kelindar/binary@v1.0.14/codecs.go:323 +0x197
github.com/kelindar/binary.(*reflectStructCodec).DecodeTo(0x10cf4e0, 0xc0000ac0a8, {0x10dbd40, 0xc0000ac0b0, 0xc0000ac0b0})
	/Users/mark/go/pkg/mod/github.com/kelindar/binary@v1.0.14/codecs.go:273 +0x148
github.com/kelindar/binary.(*reflectPointerCodec).DecodeTo(0xc000096330, 0xc000098450, {0x10cf4e0, 0xc0000ac0a8, 0xc0000a4180})
	/Users/mark/go/pkg/mod/github.com/kelindar/binary@v1.0.14/codecs.go:246 +0x15c
github.com/kelindar/binary.(*reflectSliceCodec).DecodeTo(0xc000096340, 0xc000098450, {0x10d0e20, 0xc0000a4168, 0x106bdd2})
	/Users/mark/go/pkg/mod/github.com/kelindar/binary@v1.0.14/codecs.go:94 +0x4f7
github.com/kelindar/binary.(*Decoder).Decode(0xc000098450, {0x10cea20, 0xc0000a4168})
	/Users/mark/go/pkg/mod/github.com/kelindar/binary@v1.0.14/decoder.go:71 +0x119
github.com/kelindar/binary.Unmarshal({0xc0000b6000, 0x12, 0x40}, {0x10cea20, 0xc0000a4168})
	/Users/mark/go/pkg/mod/github.com/kelindar/binary@v1.0.14/decoder.go:34 +0xba
main.main()
	/Users/mark/go2/main.go:19 +0x10f
exit status 2
```

I'm having a look at t fix, but my reflect knowledge is limited.

**Comment by Rambatino** [comment]
rv IsValid() returns false by the way
